name: Merge any release branch to main
on:
  push:
    branches:
      - 'release/*'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Merge pull -> main
        uses: devmasx/merge-branch@main
        with:
          type: now
          target_branch: main
          message: Merge pull into main
          github_token: ${{ secrets.GIT_TOKEN }}